services:
  guest:
    image: guest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://guest-mongodb:27017/Guest
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      guest-mongodb:
        condition: service_healthy
  guest-mongodb-node:
    build:
      context: src/main/docker
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --shardsvr --replSet rs1
  guest-mongodb-config:
    image: mongo:7.0.2
    container_name: guest-mongodb-config
    command: mongod --configsvr --dbpath /data/db --replSet csvr
  guest-mongodb:
    image: mongo:7.0.2
    command: mongos --configdb csvr/guest-mongodb-config --bind_ip 0.0.0.0
