# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: guest
services:
  app:
    image: guest
    labels:
      - 'traefik.http.routers.guest.rule=Host(`guest.docker.localhost`)'
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/Guest
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb

networks:
  proxy: # rename this to your custom docker network.
    driver: bridge
    external: true
